# Generated by Django 4.1.7 on 2023-03-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default=None, max_length=5),
        ),
    ]
