# Generated by Django 4.1.7 on 2023-03-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskList', '0005_alter_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.CharField(choices=[(models.CharField(max_length=200), 'Title'), (models.BooleanField(default=False), 'Completed'), (models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default=None, max_length=6), 'Priority'), (models.DateTimeField(auto_now_add=True), 'Creation')], default=models.BooleanField(default=False), max_length=8),
        ),
    ]
