# Generated by Django 4.1.7 on 2023-03-16 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskList', '0006_alter_task_options_task_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
    ]
